# Generated by Django 4.2.1 on 2024-05-18 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=300, verbose_name="Действие")),
                ("place", models.CharField(help_text="Где выполнять привычку?", max_length=250, verbose_name="Место")),
                (
                    "time",
                    models.DateTimeField(
                        help_text="В какое время выполнять привычку?", verbose_name="Время выполнения"
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Это приятная привычка?", verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(
                        default=1, help_text="Действие совершать один раз в N дней", verbose_name="Периодичность"
                    ),
                ),
                ("reward", models.CharField(max_length=300, verbose_name="Вознаграждение")),
                (
                    "action_time",
                    models.IntegerField(
                        help_text="Укажите время на выполнение привычки в минутах", verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Привычку опубликовать?", verbose_name="Признак публикации"
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="SPA.habit", verbose_name="Связанная привычка"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
