# Generated by Django 4.2.1 on 2024-05-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPA", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(help_text="В какое время выполнять привычку?", verbose_name="Время выполнения"),
        ),
    ]
