# Generated by Django 4.2.1 on 2024-05-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SPA", "0004_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="linked_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SPA.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name="Вознаграждение"),
        ),
    ]
